=== IgorRamirez/PracticaFinal_IgorRamirez/xml-resources/jaxb/javaBaloncesto/LigaBaloncestoEsquema.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" version="1.0">
	<xsd:element name="LigaBaloncesto">
		<xsd:complexType>
			<xsd:choice maxOccurs="unbounded">
				<xsd:element name="equipo" minOccurs="0" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="presidente" type="xsd:string" />
							<xsd:element name="capitan" type="xsd:string" />
							<xsd:element name="estadio" type="xsd:string" />
							<xsd:element name="colores" type="xsd:string" />
							<xsd:element name="part_ganados" type="xsd:string" />
							<xsd:element name="part_perdidos" type="xsd:string" />
							<xsd:element name="puntos_a_favor" type="xsd:string" />
							<xsd:element name="puntos_en_contra" type="xsd:string" />
						</xsd:sequence>
						<xsd:attribute name="id_equipo" type="xsd:string"/>
						<xsd:attribute name="nombre" type="xsd:string"/>
						<xsd:attribute name="puesto" type="xsd:string"/>
					</xsd:complexType>
				</xsd:element>
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== IgorRamirez/PracticaFinal_IgorRamirez/src/practicafinal_igorramirez/baloncesto.xml
<LigaBaloncesto xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="LigaBaloncestoEsquema.xsd">
	
	<equipo id_equipo="01" nombre="Real Madrid" puesto="01">	
			<presidente>Florentino PÃ©rez</presidente>
			<capitan>Felipe Reyes</capitan>
			<estadio>Wizink Center</estadio>
			<colores>Blanco-Morado</colores>
			<part_ganados>30</part_ganados>
			<part_perdidos>4</part_perdidos>
			<puntos_a_favor>3052</puntos_a_favor>
			<puntos_en_contra>2678</puntos_en_contra> 
	</equipo>
	
	<equipo id_equipo="02" nombre="San Pablo Burgos" puesto="14">	
			<presidente>Felix Sancho</presidente>
			<capitan>Bruno Fitipaldo</capitan>
			<estadio>Coliseum Burgos</estadio>
			<colores>Azul-Blanco</colores>
			<part_ganados>13</part_ganados>
			<part_perdidos>21</part_perdidos>
			<puntos_a_favor>2775</puntos_a_favor>
			<puntos_en_contra>2961</puntos_en_contra>	
	</equipo>
</LigaBaloncesto>
